package com.epgpro.model;

import java.util.Date;
/**
 * 
 * @author Administrator
 * @date 2020年4月3日上午11:15:05
 * 描述：channel实体类
 */
public class ChannelDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.id
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.name
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.callsign
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String callsign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.webtype
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String webtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.contentid
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String contentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.createtime
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.description
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.language
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.status
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.satellite
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String satellite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.showNo
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String showno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.imgurl
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel.property
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String property;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public ChannelDo(Integer id, String name, String callsign, String webtype, String contentid, Date createtime, String description, String language, Integer status, String satellite, String showno, String imgurl, String property) {
        this.id = id;
        this.name = name;
        this.callsign = callsign;
        this.webtype = webtype;
        this.contentid = contentid;
        this.createtime = createtime;
        this.description = description;
        this.language = language;
        this.status = status;
        this.satellite = satellite;
        this.showno = showno;
        this.imgurl = imgurl;
        this.property = property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public ChannelDo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.id
     *
     * @return the value of channel.id
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.id
     *
     * @param id the value for channel.id
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.name
     *
     * @return the value of channel.name
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.name
     *
     * @param name the value for channel.name
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.callsign
     *
     * @return the value of channel.callsign
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getCallsign() {
        return callsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.callsign
     *
     * @param callsign the value for channel.callsign
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setCallsign(String callsign) {
        this.callsign = callsign == null ? null : callsign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.webtype
     *
     * @return the value of channel.webtype
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getWebtype() {
        return webtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.webtype
     *
     * @param webtype the value for channel.webtype
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setWebtype(String webtype) {
        this.webtype = webtype == null ? null : webtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.contentid
     *
     * @return the value of channel.contentid
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getContentid() {
        return contentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.contentid
     *
     * @param contentid the value for channel.contentid
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setContentid(String contentid) {
        this.contentid = contentid == null ? null : contentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.createtime
     *
     * @return the value of channel.createtime
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.createtime
     *
     * @param createtime the value for channel.createtime
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.description
     *
     * @return the value of channel.description
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.description
     *
     * @param description the value for channel.description
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.language
     *
     * @return the value of channel.language
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.language
     *
     * @param language the value for channel.language
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.status
     *
     * @return the value of channel.status
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.status
     *
     * @param status the value for channel.status
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.satellite
     *
     * @return the value of channel.satellite
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getSatellite() {
        return satellite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.satellite
     *
     * @param satellite the value for channel.satellite
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setSatellite(String satellite) {
        this.satellite = satellite == null ? null : satellite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.showNo
     *
     * @return the value of channel.showNo
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getShowno() {
        return showno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.showNo
     *
     * @param showno the value for channel.showNo
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setShowno(String showno) {
        this.showno = showno == null ? null : showno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.imgurl
     *
     * @return the value of channel.imgurl
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.imgurl
     *
     * @param imgurl the value for channel.imgurl
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel.property
     *
     * @return the value of channel.property
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel.property
     *
     * @param property the value for channel.property
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }

	@Override
	public String toString() {
		return "ChannelDo [id=" + id + ", name=" + name + ", callsign=" + callsign + ", webtype=" + webtype
				+ ", contentid=" + contentid + ", createtime=" + createtime + ", description=" + description
				+ ", language=" + language + ", status=" + status + ", satellite=" + satellite + ", showno=" + showno
				+ ", imgurl=" + imgurl + ", property=" + property + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((callsign == null) ? 0 : callsign.hashCode());
		result = prime * result + ((contentid == null) ? 0 : contentid.hashCode());
		result = prime * result + ((createtime == null) ? 0 : createtime.hashCode());
		result = prime * result + ((description == null) ? 0 : description.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((imgurl == null) ? 0 : imgurl.hashCode());
		result = prime * result + ((language == null) ? 0 : language.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + ((property == null) ? 0 : property.hashCode());
		result = prime * result + ((satellite == null) ? 0 : satellite.hashCode());
		result = prime * result + ((showno == null) ? 0 : showno.hashCode());
		result = prime * result + ((status == null) ? 0 : status.hashCode());
		result = prime * result + ((webtype == null) ? 0 : webtype.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ChannelDo other = (ChannelDo) obj;
		if (callsign == null) {
			if (other.callsign != null)
				return false;
		} else if (!callsign.equals(other.callsign))
			return false;
		if (contentid == null) {
			if (other.contentid != null)
				return false;
		} else if (!contentid.equals(other.contentid))
			return false;
		if (createtime == null) {
			if (other.createtime != null)
				return false;
		} else if (!createtime.equals(other.createtime))
			return false;
		if (description == null) {
			if (other.description != null)
				return false;
		} else if (!description.equals(other.description))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (imgurl == null) {
			if (other.imgurl != null)
				return false;
		} else if (!imgurl.equals(other.imgurl))
			return false;
		if (language == null) {
			if (other.language != null)
				return false;
		} else if (!language.equals(other.language))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		if (property == null) {
			if (other.property != null)
				return false;
		} else if (!property.equals(other.property))
			return false;
		if (satellite == null) {
			if (other.satellite != null)
				return false;
		} else if (!satellite.equals(other.satellite))
			return false;
		if (showno == null) {
			if (other.showno != null)
				return false;
		} else if (!showno.equals(other.showno))
			return false;
		if (status == null) {
			if (other.status != null)
				return false;
		} else if (!status.equals(other.status))
			return false;
		if (webtype == null) {
			if (other.webtype != null)
				return false;
		} else if (!webtype.equals(other.webtype))
			return false;
		return true;
	}
    
}