package com.epgpro.model;

import java.util.Date;

/**
 * 
 * @author Administrator
 * @date 2020年4月3日上午11:15:26
 * 描述：schedule实体类
 */
public class ScheduleDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.id
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.channelid
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private Integer channelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.contentid
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String contentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.programname
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String programname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.startdate
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private Date startdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.starttime
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.endtime
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.duration
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.description
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.imgurl
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String imgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.createtime
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.language
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.satellite
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String satellite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.property
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String property;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.videourl
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private String videourl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule.source
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    private Integer source;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public ScheduleDo(Integer id, Integer channelid, String contentid, String programname, Date startdate, Date starttime, Date endtime, String duration, String description, String imgurl, Date createtime, String language, String satellite, String property, String videourl, Integer source) {
        this.id = id;
        this.channelid = channelid;
        this.contentid = contentid;
        this.programname = programname;
        this.startdate = startdate;
        this.starttime = starttime;
        this.endtime = endtime;
        this.duration = duration;
        this.description = description;
        this.imgurl = imgurl;
        this.createtime = createtime;
        this.language = language;
        this.satellite = satellite;
        this.property = property;
        this.videourl = videourl;
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public ScheduleDo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.id
     *
     * @return the value of schedule.id
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.id
     *
     * @param id the value for schedule.id
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.channelid
     *
     * @return the value of schedule.channelid
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public Integer getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.channelid
     *
     * @param channelid the value for schedule.channelid
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setChannelid(Integer channelid) {
        this.channelid = channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.contentid
     *
     * @return the value of schedule.contentid
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getContentid() {
        return contentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.contentid
     *
     * @param contentid the value for schedule.contentid
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setContentid(String contentid) {
        this.contentid = contentid == null ? null : contentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.programname
     *
     * @return the value of schedule.programname
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getProgramname() {
        return programname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.programname
     *
     * @param programname the value for schedule.programname
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setProgramname(String programname) {
        this.programname = programname == null ? null : programname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.startdate
     *
     * @return the value of schedule.startdate
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.startdate
     *
     * @param startdate the value for schedule.startdate
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.starttime
     *
     * @return the value of schedule.starttime
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.starttime
     *
     * @param starttime the value for schedule.starttime
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.endtime
     *
     * @return the value of schedule.endtime
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.endtime
     *
     * @param endtime the value for schedule.endtime
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.duration
     *
     * @return the value of schedule.duration
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.duration
     *
     * @param duration the value for schedule.duration
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setDuration(String duration) {
        this.duration = duration == null ? null : duration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.description
     *
     * @return the value of schedule.description
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.description
     *
     * @param description the value for schedule.description
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.imgurl
     *
     * @return the value of schedule.imgurl
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.imgurl
     *
     * @param imgurl the value for schedule.imgurl
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.createtime
     *
     * @return the value of schedule.createtime
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.createtime
     *
     * @param createtime the value for schedule.createtime
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.language
     *
     * @return the value of schedule.language
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.language
     *
     * @param language the value for schedule.language
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.satellite
     *
     * @return the value of schedule.satellite
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getSatellite() {
        return satellite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.satellite
     *
     * @param satellite the value for schedule.satellite
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setSatellite(String satellite) {
        this.satellite = satellite == null ? null : satellite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.property
     *
     * @return the value of schedule.property
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.property
     *
     * @param property the value for schedule.property
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.videourl
     *
     * @return the value of schedule.videourl
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public String getVideourl() {
        return videourl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.videourl
     *
     * @param videourl the value for schedule.videourl
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setVideourl(String videourl) {
        this.videourl = videourl == null ? null : videourl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule.source
     *
     * @return the value of schedule.source
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule.source
     *
     * @param source the value for schedule.source
     *
     * @mbg.generated Wed Apr 01 18:06:24 CST 2020
     */
    public void setSource(Integer source) {
        this.source = source;
    }

	@Override
	public String toString() {
		return "ScheduleDo [id=" + id + ", channelid=" + channelid + ", contentid=" + contentid + ", programname="
				+ programname + ", startdate=" + startdate + ", starttime=" + starttime + ", endtime=" + endtime
				+ ", duration=" + duration + ", description=" + description + ", imgurl=" + imgurl + ", createtime="
				+ createtime + ", language=" + language + ", satellite=" + satellite + ", property=" + property
				+ ", videourl=" + videourl + ", source=" + source + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((channelid == null) ? 0 : channelid.hashCode());
		result = prime * result + ((contentid == null) ? 0 : contentid.hashCode());
		result = prime * result + ((createtime == null) ? 0 : createtime.hashCode());
		result = prime * result + ((description == null) ? 0 : description.hashCode());
		result = prime * result + ((duration == null) ? 0 : duration.hashCode());
		result = prime * result + ((endtime == null) ? 0 : endtime.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((imgurl == null) ? 0 : imgurl.hashCode());
		result = prime * result + ((language == null) ? 0 : language.hashCode());
		result = prime * result + ((programname == null) ? 0 : programname.hashCode());
		result = prime * result + ((property == null) ? 0 : property.hashCode());
		result = prime * result + ((satellite == null) ? 0 : satellite.hashCode());
		result = prime * result + ((source == null) ? 0 : source.hashCode());
		result = prime * result + ((startdate == null) ? 0 : startdate.hashCode());
		result = prime * result + ((starttime == null) ? 0 : starttime.hashCode());
		result = prime * result + ((videourl == null) ? 0 : videourl.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ScheduleDo other = (ScheduleDo) obj;
		if (channelid == null) {
			if (other.channelid != null)
				return false;
		} else if (!channelid.equals(other.channelid))
			return false;
		if (contentid == null) {
			if (other.contentid != null)
				return false;
		} else if (!contentid.equals(other.contentid))
			return false;
		if (createtime == null) {
			if (other.createtime != null)
				return false;
		} else if (!createtime.equals(other.createtime))
			return false;
		if (description == null) {
			if (other.description != null)
				return false;
		} else if (!description.equals(other.description))
			return false;
		if (duration == null) {
			if (other.duration != null)
				return false;
		} else if (!duration.equals(other.duration))
			return false;
		if (endtime == null) {
			if (other.endtime != null)
				return false;
		} else if (!endtime.equals(other.endtime))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (imgurl == null) {
			if (other.imgurl != null)
				return false;
		} else if (!imgurl.equals(other.imgurl))
			return false;
		if (language == null) {
			if (other.language != null)
				return false;
		} else if (!language.equals(other.language))
			return false;
		if (programname == null) {
			if (other.programname != null)
				return false;
		} else if (!programname.equals(other.programname))
			return false;
		if (property == null) {
			if (other.property != null)
				return false;
		} else if (!property.equals(other.property))
			return false;
		if (satellite == null) {
			if (other.satellite != null)
				return false;
		} else if (!satellite.equals(other.satellite))
			return false;
		if (source == null) {
			if (other.source != null)
				return false;
		} else if (!source.equals(other.source))
			return false;
		if (startdate == null) {
			if (other.startdate != null)
				return false;
		} else if (!startdate.equals(other.startdate))
			return false;
		if (starttime == null) {
			if (other.starttime != null)
				return false;
		} else if (!starttime.equals(other.starttime))
			return false;
		if (videourl == null) {
			if (other.videourl != null)
				return false;
		} else if (!videourl.equals(other.videourl))
			return false;
		return true;
	}
    
}